name: Feature Request
description: Request a new feature or functionality
labels: [feature request]
title: "[FEATURE REQUEST] - <title>"
body:

  - type: textarea
    id: feature-description
    attributes:
      label: Describe your suggested feature
      description: How can Chouten be improved?
      placeholder: |
        Example:
          "It should work like this..."
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Examples
      placeholder: |
        Found an open source app that already implements this or documentation on it?
        Put a link to it or if it's an idea for the ui a screenshot or screen recording here

  - type: textarea
    id: other-details
    attributes:
      label: Other details
      placeholder: |
        Additional details and attachments.

  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      description: Read this carefully, we will close and ignore your issue if you skimmed through this.
      options:
        - label: I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
          required: true
        - label: I have written a short but informative title.
          required: true
        - label: I have updated the app to the **latest version**.
          required: true